spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service-static
          uri: lb://USER-SERVICE # it will do load balancing between instaces
          predicates:
            - Path=/users/**       # requests to /users/** -> user-service
          filters:
            - StripPrefix=0

        - id: orders-static
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**      # example static route to orders service
          filters:
            - StripPrefix=0
